name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Check linter and prettier
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Deploy to gitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
